config/routes.rb
MyFirstRails::Application.routes.draw do
  resources :tweets, only: [:index, :destroy, :create, :show]

  resources :people, only: [:index, :show] do
    member do
      post 'follow'   => 'people#follow'
      delete 'follow'  => 'people#unfollow'
    end
  end

  authenticated :user do
    root :to => 'welcome#index', :as => :authenticated_root
  end
  root :to => redirect('/users/sign_in')

  devise_for :users

  

end

app/models/at_user.rb
class AtUser < ActiveRecord::Base
  belongs_to :user
  belongs_to :tweet
  validates_presence_of :user
  validates_presence_of :tweet

end

app/models/following.rb
class Following < ActiveRecord::Base

  belongs_to :follower_users, class_name: :User
  belongs_to :followed_users, class_name: :User
  validates :follower_users_id, presence: true
  validates :followed_users_id, presence: true
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :text
  validates_length_of :text, :in => 1..200
  validates_presence_of :user

  has_many :at_users, foreign_key: :tweet_id, dependent: :destroy
  has_many :to_users, through: :at_users, source: :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tweets, foreign_key: :user_id, dependent: :destroy
  has_many :followed_users, through: :followings, source: :follower_users
  has_many :follower_users, through: :followerings, source: :followed_users
  has_many :followings, foreign_key: :followed_users_id, dependent: :destroy
  has_many :followerings, foreign_key: :follower_users_id, class_name: :Following, dependent: :destroy

  has_many :at_users, foreign_key: :user_id, dependent: :destroy
  has_many :tweets_at_user, through: :at_users, source: :tweet

  def follow!(other_user)
    followings.create!(follower_users_id: other_user.id)
  end

  def following?(other_user)
    followings.find_by(follower_users_id: other_user.id)
  end

  def unfollow!(other_user)
     followings.find_by(follower_users_id: other_user.id).destroy!
  end

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessor :login

  validates :username,
            :uniqueness => {
                :case_sensitive => false
            }
  validates :email,
            :uniqueness => {
                :case_sensitive => false
            }

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?
  before_filter :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :password, :remember_me) }
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:login,:username, :email, :password, :password_confirmation, :remember_me) }
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def show
    user = User.find_by_username(params[:id])
    tweets = user.tweets
    followed = user.followed_users
    tweets_at_users = user.tweets_at_user
    follower = user.follower_users

    @person = {:user => user, :tweets => tweets, :tweets_at_user => tweets_at_users, :following => followed, :followers => follower}
    respond_to do |format|
      format.xml { render :xml => @person}
      format.json { render :json => @person}
      format.html { render :view }
    end
  end

  def index
    @users = User.all
    respond_to do |format|
      format.xml { render :xml => @users}
      format.html { render :all }
      format.json { render :json => @users}
    end
  end

  #user will be following the user associated with :handle after this call, it doesnt the about their following state
  def follow
    user = User.find_by_username(params[:id])
    if !current_user.following?(user)
      current_user.follow!(user)
    end
    respond_to do |format|
      format.json { render :json => true, :status => :ok }
      format.xml { render :xml => true, :status => :ok }
      format.html { redirect_to person_url(params[:id])}
    end
  end

  #user will no long be following the user associated with :handle, it doesnt the about their following state
  def unfollow
    user = User.find_by_username(params[:id])
    if current_user.following?(user)
      current_user.unfollow!(user)
    end
    respond_to do |format|
      format.json { render :json => true, :status => :ok }
      format.xml { render :xml => true, :status => :ok }
      format.html { redirect_to person_url(params[:id])}
    end
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def show
    @tweet = Tweet.find(params[:id])
    @to_users = @tweet.to_users
    respond_to do |format|
      format.xml { render :xml => {:tweet => @tweet, :to_users => @to_users } }
      format.json { render :json => {:tweet => @tweet, :to_users => @to_users } }
      format.html { render :view }
    end
  end

  def index
    @tweets = Tweet.all
    respond_to do |format|
      format.xml { render :xml => @tweets }
      format.json { render :json => @tweets }
      format.html { render :all }
    end
  end


  def destroy
    tweet = Tweet.find(params[:id])
    if current_user == tweet.user
      tweet.destroy!
      respond_to do |format|
        format.json { render :json => true, :status => :ok }
        format.xml { render :xml => true, :status => :ok }
        format.html { redirect_to root_url }
      end

    else
      head :unauthorized
    end

  end

  def create
    @tweet = current_user.tweets.create(text: params[:tweet][:text])
    if @tweet.valid?
      at_users = @tweet.text.scan(/@([a-z0-9_]+)/i)
      #think im missing something here.  why does this each fill u with a single entry array?
      at_users.each {|u|
        user = User.find_by_username(params[:id])
        @tweet.at_users.create({:user_id => user.id})
      }
      respond_to do |format|
        format.json { render :json => @tweet }
        format.xml { render :xml => @tweet }
        format.html { redirect_to root_url }
      end
    else
      respond_to do |format|
        format.json { render :json => @tweet.errors, :status => :bad_request }
        format.xml { render :xml => @tweet.errors, :status => :bad_request }
        format.html { redirect_to root_url, :flash => { :alert => @tweet.errors[:text] } }
      end
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    redirect_to person_url(current_user.username)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyFirstRails</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if notice %>
    <p class="alert alert-notice"><%= notice %></p>
<% end %>
<% if alert %>
    <p class="alert alert-error"><%= alert %></p>
<% end %>
<% if user_signed_in? %>

    <%=  link_to t('navigation.home'), root_path %>
    <%=  link_to t('navigation.people'), people_path %>
    <%=  link_to t('navigation.tweet'), tweets_path %>
    <%= link_to(t('navigation.logout'), destroy_user_session_path, :method => :delete) %>

    <%= form_for Tweet.new, {:url => {controller: "tweets", action: "create"}, :remote => true} do |f| %>
        <%= f.text_field :text %>
        <%= f.submit t('tweet'), {id: 'submit-tweet'} %>
    <% end %>
<% end %>
<%= yield %>

</body>
</html>

app/views/people/all.html.erb
<% @users.each do |u| %>

    <%= link_to u.username, person_url(u.username) %>
<% end %>

app/views/people/view.html.erb
<div>User Info</div>
<div><%= @person[:user].email %></div>
<div>Tweets</div>
<div>
  <% @person[:tweets].each do |tweet| %>
      <div>
        <%= tweet.text %>
        <% if @person[:user] == current_user %>
            <%= form_tag(tweet_url(tweet), method: 'delete', remote: true, class: 'delete-tweet') do %>
                <%= submit_tag(:Delete) %>
            <% end %>
        <% end %>
      </div>
  <% end %>
</div>
<% if @person[:user] == current_user %>
    <%= t('people.yourprofile') %>
<% else %>

    <%= form_tag(follow_person_url(params[:id]), :id => 'follow', :remote => true) do %>
        <%= submit_tag t('people.follow'), :id => 'follow-button' %>
    <% end %>
    <%= form_tag(follow_person_url(params[:id]), :method => 'delete', :id => 'unfollow', :remote => true) do %>
        <%= submit_tag t('people.unfollow'), :id => 'unfollow-button' %>
    <% end %>
    <%# inline some js here to show/hide the appropiate button %>
    <script type="text/javascript">
        $('<%= current_user.following?(@person[:user]) ? '#follow-button' : '#unfollow-button' %>').hide()
    </script>
<% end %>

<div>
  <% if current_user == @person[:user] %>You are
      <% else %><%= "#{params[:id]} is" %>
  <% end %> following these users
  <% @person[:following].each do |f| %>
      <% user_handle = f.email.slice 0, f.email.index('@') %>
      <div><%= link_to user_handle, user_handle %></div>
  <% end %>
</div>
<div>
  These users are following
  <% if current_user == @person[:user] %>you
      <% else %><%= params[:id] %>
  <% end %>
  <% @person[:followers].each do |f| %>

      <% user_handle = f.email.slice 0, f.email.index('@') %>
      <div><%= link_to user_handle, user_handle %></div>
  <% end %>
</div>

app/views/tweets/all.html.erb
<% @tweets.each do |t| %>
<div><%= link_to t.text, tweet_url(id: t.id) %></div>
<% end %>

app/views/tweets/view.html.erb
<%= @tweet.attributes %>